# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  BuildPlatform: 'x64'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build ** C# Projects'
  inputs:
    command: 'build'
    platform: $(BuildPlatform)
    arguments: '--no-restore --configuration $(BuildConfiguration)'
    projects: '**/*.csproj'

- task: VSTest@2
  inputs:
    platform: '$(BuildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish Web Projects'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--no-restore --no-build --configuration $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)'
    workingDirectory: '$(System.DefaultWorkingDirectory)'