# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  BuildPlatform: 'x64'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'WebAppWithDatabaseDemo'
    organization: 'mahmoudsalah0502'
    scannerMode: 'MSBuild'
    projectKey: 'Mahmoudsalah0502_DotNet-Core-Mvc-App'
    projectName: 'DotNet-Core-Mvc-App'

- task: DotNetCoreCLI@2
  displayName: 'Build ** C# Projects'
  inputs:
    command: 'build'
    platform: $(BuildPlatform)
    arguments: '--no-restore --configuration $(BuildConfiguration)'
    projects: '**/*.csproj'

- task: VSTest@2
  inputs:
    platform: '$(BuildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'WebAppWithDatabaseDemo'